//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace au.Applications.MythClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("au.Applications.MythClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About18 {
            get {
                object obj = ResourceManager.GetObject("About18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download....
        /// </summary>
        internal static string ActionExport {
            get {
                return ResourceManager.GetString("ActionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string ActionPlay {
            get {
                return ResourceManager.GetString("ActionPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play with....
        /// </summary>
        internal static string ActionPlayWith {
            get {
                return ResourceManager.GetString("ActionPlayWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back24 {
            get {
                object obj = ResourceManager.GetObject("Back24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackDisabled24 {
            get {
                object obj = ResourceManager.GetObject("BackDisabled24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to {0}.
        /// </summary>
        internal static string BackTo {
            get {
                return ResourceManager.GetString("BackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Date18 {
            get {
                object obj = ResourceManager.GetObject("Date18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete18 {
            get {
                object obj = ResourceManager.GetObject("Delete18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete{0}MythTV will not record this episode again..
        /// </summary>
        internal static string DeleteOption {
            get {
                return ResourceManager.GetString("DeleteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete + Rerecord{0}MythTV will record this episode if it comes on again..
        /// </summary>
        internal static string DeleteRerecordOption {
            get {
                return ResourceManager.GetString("DeleteRerecordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export18 {
            get {
                object obj = ResourceManager.GetObject("Export18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({2:yyyy.MM.dd}).
        /// </summary>
        internal static string ExportDate {
            get {
                return ResourceManager.GetString("ExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {2:yyyy.MM.dd} - {1}.
        /// </summary>
        internal static string ExportDateEpisode {
            get {
                return ResourceManager.GetString("ExportDateEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string ExportEpisode {
            get {
                return ResourceManager.GetString("ExportEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdate.
        /// </summary>
        internal static string ExportOptionDate {
            get {
                return ResourceManager.GetString("ExportOptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdate.
        /// </summary>
        internal static string ExportOptionDateEpisode {
            get {
                return ResourceManager.GetString("ExportOptionDateEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title - Subtitle.
        /// </summary>
        internal static string ExportOptionEpisode {
            get {
                return ResourceManager.GetString("ExportOptionEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season / Episode.
        /// </summary>
        internal static string ExportOptionSeasonEpisode {
            get {
                return ResourceManager.GetString("ExportOptionSeasonEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ExportOptionTitle {
            get {
                return ResourceManager.GetString("ExportOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ExportOptionYear {
            get {
                return ResourceManager.GetString("ExportOptionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - s{3:00}e{4:00} - {1}.
        /// </summary>
        internal static string ExportSeasonEpisode {
            get {
                return ResourceManager.GetString("ExportSeasonEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({2:yyyy}).
        /// </summary>
        internal static string ExportYear {
            get {
                return ResourceManager.GetString("ExportYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Aired {0:M/d/yyyy}.
        /// </summary>
        internal static string InfoEpisodeFirstAired {
            get {
                return ResourceManager.GetString("InfoEpisodeFirstAired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode {0}.
        /// </summary>
        internal static string InfoEpisodeNumber {
            get {
                return ResourceManager.GetString("InfoEpisodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded {0:M/d/yyyy h:mm tt}.
        /// </summary>
        internal static string InfoEpisodeRecorded {
            get {
                return ResourceManager.GetString("InfoEpisodeRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}, Episode {1}.
        /// </summary>
        internal static string InfoEpisodeSeasonEpisode {
            get {
                return ResourceManager.GetString("InfoEpisodeSeasonEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing in {0}.
        /// </summary>
        internal static string InfoEpisodeStillRecording {
            get {
                return ResourceManager.GetString("InfoEpisodeStillRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:  {1}.
        /// </summary>
        internal static string InfoEpisodeTitle {
            get {
                return ResourceManager.GetString("InfoEpisodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1:M/d/yyyy}.
        /// </summary>
        internal static string InfoEpisodeTitleNameless {
            get {
                return ResourceManager.GetString("InfoEpisodeTitleNameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1:yyyy}).
        /// </summary>
        internal static string InfoMovieTitle {
            get {
                return ResourceManager.GetString("InfoMovieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Episodes.
        /// </summary>
        internal static string InfoNumEpisodes {
            get {
                return ResourceManager.GetString("InfoNumEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Seasons.
        /// </summary>
        internal static string InfoNumSeasons {
            get {
                return ResourceManager.GetString("InfoNumSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:M/d/yyyy} — {1:M/d/yyyy}.
        /// </summary>
        internal static string InfoRecordedRange {
            get {
                return ResourceManager.GetString("InfoRecordedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Season {1}.
        /// </summary>
        internal static string InfoSeasonTitle {
            get {
                return ResourceManager.GetString("InfoSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record this episode again?.
        /// </summary>
        internal static string InstrDelete {
            get {
                return ResourceManager.GetString("InstrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file naming option..
        /// </summary>
        internal static string InstrExport {
            get {
                return ResourceManager.GetString("InstrExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu24 {
            get {
                object obj = ResourceManager.GetObject("Menu24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MythTV32 {
            get {
                object obj = ResourceManager.GetObject("MythTV32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this recording was in some way unsatisfactory, MythTV can record it again the next time it comes on..
        /// </summary>
        internal static string NoteDelete {
            get {
                return ResourceManager.GetString("NoteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file format and extension will be left unchanged..
        /// </summary>
        internal static string NoteExport {
            get {
                return ResourceManager.GetString("NoteExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play18 {
            get {
                object obj = ResourceManager.GetObject("Play18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayWith18 {
            get {
                object obj = ResourceManager.GetObject("PlayWith18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Recordings.
        /// </summary>
        internal static string RecordedEpisodes {
            get {
                return ResourceManager.GetString("RecordedEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Season {1} Episodes.
        /// </summary>
        internal static string RecordedSeasonEpisodes {
            get {
                return ResourceManager.GetString("RecordedSeasonEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Seasons.
        /// </summary>
        internal static string RecordedSeasons {
            get {
                return ResourceManager.GetString("RecordedSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Shows.
        /// </summary>
        internal static string RecordedShows {
            get {
                return ResourceManager.GetString("RecordedShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reload24 {
            get {
                object obj = ResourceManager.GetObject("Reload24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings18 {
            get {
                object obj = ResourceManager.GetObject("Settings18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SortDate24 {
            get {
                object obj = ResourceManager.GetObject("SortDate24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SortTitle24 {
            get {
                object obj = ResourceManager.GetObject("SortTitle24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Static1080p {
            get {
                object obj = ResourceManager.GetObject("Static1080p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours.
        /// </summary>
        internal static string TimeSpanHours {
            get {
                return ResourceManager.GetString("TimeSpanHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours {1:0} minutes.
        /// </summary>
        internal static string TimeSpanHoursMinutes {
            get {
                return ResourceManager.GetString("TimeSpanHoursMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minutes.
        /// </summary>
        internal static string TimeSpanMinutes {
            get {
                return ResourceManager.GetString("TimeSpanMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} from MythTV.
        /// </summary>
        internal static string TipDelete {
            get {
                return ResourceManager.GetString("TipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the oldest recorded episode of this season.
        /// </summary>
        internal static string TipDeleteOldestSeason {
            get {
                return ResourceManager.GetString("TipDeleteOldestSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the oldest recorded episode of this show.
        /// </summary>
        internal static string TipDeleteOldestShow {
            get {
                return ResourceManager.GetString("TipDeleteOldestShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} with a readable filename.
        /// </summary>
        internal static string TipExportEpisode {
            get {
                return ResourceManager.GetString("TipExportEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all episodes from this season with readable filenames.
        /// </summary>
        internal static string TipExportSeason {
            get {
                return ResourceManager.GetString("TipExportSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all episodes from this show with readable filenames.
        /// </summary>
        internal static string TipExportShow {
            get {
                return ResourceManager.GetString("TipExportShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0} with the default video player.
        /// </summary>
        internal static string TipPlay {
            get {
                return ResourceManager.GetString("TipPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the oldest recorded episode of this season.
        /// </summary>
        internal static string TipPlayOldestSeason {
            get {
                return ResourceManager.GetString("TipPlayOldestSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an alternate player to play the oldest recorded episode of this season.
        /// </summary>
        internal static string TipPlayOldestSeasonWith {
            get {
                return ResourceManager.GetString("TipPlayOldestSeasonWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the oldest recorded episode of this show.
        /// </summary>
        internal static string TipPlayOldestShow {
            get {
                return ResourceManager.GetString("TipPlayOldestShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an alternate player to play the oldest recorded episode of this show.
        /// </summary>
        internal static string TipPlayOldestShowWith {
            get {
                return ResourceManager.GetString("TipPlayOldestShowWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an alternate player to play {0}.
        /// </summary>
        internal static string TipPlayWith {
            get {
                return ResourceManager.GetString("TipPlayWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Title18 {
            get {
                object obj = ResourceManager.GetObject("Title18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recording.
        /// </summary>
        internal static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Recording.
        /// </summary>
        internal static string TitleExportOne {
            get {
                return ResourceManager.GetString("TitleExportOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Recordings.
        /// </summary>
        internal static string TitleExportPlural {
            get {
                return ResourceManager.GetString("TitleExportPlural", resourceCulture);
            }
        }
    }
}
