//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace au.Applications.MythClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("au.Applications.MythClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackDisabled {
            get {
                object obj = ResourceManager.GetObject("BackDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to {0}.
        /// </summary>
        internal static string BackTo {
            get {
                return ResourceManager.GetString("BackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Aired {0:M/d/yyyy}.
        /// </summary>
        internal static string InfoEpisodeFirstAired {
            get {
                return ResourceManager.GetString("InfoEpisodeFirstAired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded {0:M/d/yyyy h:mm tt}.
        /// </summary>
        internal static string InfoEpisodeRecorded {
            get {
                return ResourceManager.GetString("InfoEpisodeRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}, Episode {1}.
        /// </summary>
        internal static string InfoEpisodeSeasonEpisode {
            get {
                return ResourceManager.GetString("InfoEpisodeSeasonEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing in {0}.
        /// </summary>
        internal static string InfoEpisodeStillRecording {
            get {
                return ResourceManager.GetString("InfoEpisodeStillRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:  {1}.
        /// </summary>
        internal static string InfoEpisodeTitle {
            get {
                return ResourceManager.GetString("InfoEpisodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Episodes.
        /// </summary>
        internal static string InfoNumEpisodes {
            get {
                return ResourceManager.GetString("InfoNumEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Seasons.
        /// </summary>
        internal static string InfoNumSeasons {
            get {
                return ResourceManager.GetString("InfoNumSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:M/d/yyyy} — {1:M/d/yyyy}.
        /// </summary>
        internal static string InfoRecordedRange {
            get {
                return ResourceManager.GetString("InfoRecordedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Season {1}.
        /// </summary>
        internal static string InfoSeasonTitle {
            get {
                return ResourceManager.GetString("InfoSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu {
            get {
                object obj = ResourceManager.GetObject("Menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MythTV {
            get {
                object obj = ResourceManager.GetObject("MythTV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayWith {
            get {
                object obj = ResourceManager.GetObject("PlayWith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Recordings.
        /// </summary>
        internal static string RecordedEpisodes {
            get {
                return ResourceManager.GetString("RecordedEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Season {1} Episodes.
        /// </summary>
        internal static string RecordedSeasonEpisodes {
            get {
                return ResourceManager.GetString("RecordedSeasonEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Seasons.
        /// </summary>
        internal static string RecordedSeasons {
            get {
                return ResourceManager.GetString("RecordedSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Shows.
        /// </summary>
        internal static string RecordedShows {
            get {
                return ResourceManager.GetString("RecordedShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Static1080p {
            get {
                object obj = ResourceManager.GetObject("Static1080p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours.
        /// </summary>
        internal static string TimeSpanHours {
            get {
                return ResourceManager.GetString("TimeSpanHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours {1:0} minutes.
        /// </summary>
        internal static string TimeSpanHoursMinutes {
            get {
                return ResourceManager.GetString("TimeSpanHoursMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minutes.
        /// </summary>
        internal static string TimeSpanMinutes {
            get {
                return ResourceManager.GetString("TimeSpanMinutes", resourceCulture);
            }
        }
    }
}
