//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace au.Applications.MythClient.UI {
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ActionText {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ActionText() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if(object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("au.Applications.MythClient.UI.ActionText", typeof(ActionText).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose a directory for downloaded recordings..
		/// </summary>
		internal static string ChooseExportFolderDescription {
			get {
				return ResourceManager.GetString("ChooseExportFolderDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete all.
		/// </summary>
		internal static string DeleteAllCaption {
			get {
				return ResourceManager.GetString("DeleteAllCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Record these again?.
		/// </summary>
		internal static string DeleteAllInstructions {
			get {
				return ResourceManager.GetString("DeleteAllInstructions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Dele&amp;te all episodes....
		/// </summary>
		internal static string DeleteAllMenu {
			get {
				return ResourceManager.GetString("DeleteAllMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to If these recordings were in some way unsatisfactory, MythTV can record them again the next time they come on..
		/// </summary>
		internal static string DeleteAllNote {
			get {
				return ResourceManager.GetString("DeleteAllNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete Recording.
		/// </summary>
		internal static string DeleteAllTitle {
			get {
				return ResourceManager.GetString("DeleteAllTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		internal static string DeleteCaption {
			get {
				return ResourceManager.GetString("DeleteCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete {0} from MythTV..
		/// </summary>
		internal static string DeleteEpisodeTooltip {
			get {
				return ResourceManager.GetString("DeleteEpisodeTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Record this again?.
		/// </summary>
		internal static string DeleteInstructions {
			get {
				return ResourceManager.GetString("DeleteInstructions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Delete.
		/// </summary>
		internal static string DeleteMenu {
			get {
				return ResourceManager.GetString("DeleteMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Delete next episode.
		/// </summary>
		internal static string DeleteNextMenu {
			get {
				return ResourceManager.GetString("DeleteNextMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to If this recording was in some way unsatisfactory, MythTV can record it again the next time it comes on..
		/// </summary>
		internal static string DeleteNote {
			get {
				return ResourceManager.GetString("DeleteNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MythTV will not record this again..
		/// </summary>
		internal static string DeleteOptionDescription {
			get {
				return ResourceManager.GetString("DeleteOptionDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MythTV will not record these again..
		/// </summary>
		internal static string DeleteOptionDescriptionPlural {
			get {
				return ResourceManager.GetString("DeleteOptionDescriptionPlural", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		internal static string DeleteOptionTitle {
			get {
				return ResourceManager.GetString("DeleteOptionTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MythTV will record this if it comes on again..
		/// </summary>
		internal static string DeleteRerecordOptionDescription {
			get {
				return ResourceManager.GetString("DeleteRerecordOptionDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MythTV will record these if they come on again..
		/// </summary>
		internal static string DeleteRerecordOptionDescriptionPlural {
			get {
				return ResourceManager.GetString("DeleteRerecordOptionDescriptionPlural", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete + Rerecord.
		/// </summary>
		internal static string DeleteRerecordOptionTitle {
			get {
				return ResourceManager.GetString("DeleteRerecordOptionTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete the oldest recorded episode of this season..
		/// </summary>
		internal static string DeleteSeasonOldestTooltip {
			get {
				return ResourceManager.GetString("DeleteSeasonOldestTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete the oldest recorded episode of this show..
		/// </summary>
		internal static string DeleteShowOldestTooltip {
			get {
				return ResourceManager.GetString("DeleteShowOldestTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete all episodes of this show..
		/// </summary>
		internal static string DeleteShowTooltip {
			get {
				return ResourceManager.GetString("DeleteShowTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete Recording.
		/// </summary>
		internal static string DeleteTitle {
			get {
				return ResourceManager.GetString("DeleteTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Dow&amp;nload all episodes....
		/// </summary>
		internal static string ExportAllMenu {
			get {
				return ResourceManager.GetString("ExportAllMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Download Recordings.
		/// </summary>
		internal static string ExportAllTitle {
			get {
				return ResourceManager.GetString("ExportAllTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Download....
		/// </summary>
		internal static string ExportCaption {
			get {
				return ResourceManager.GetString("ExportCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Export {0} with a readable filename..
		/// </summary>
		internal static string ExportEpisodeTooltip {
			get {
				return ResourceManager.GetString("ExportEpisodeTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TV Recording.
		/// </summary>
		internal static string ExportFiletype {
			get {
				return ResourceManager.GetString("ExportFiletype", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} {2:yyyy&apos;-&apos;MM&apos;-&apos;dd}.
		/// </summary>
		internal static string ExportFormatDate {
			get {
				return ResourceManager.GetString("ExportFormatDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} - {2:yyyy&apos;-&apos;MM&apos;-&apos;dd} - {1}.
		/// </summary>
		internal static string ExportFormatDateEpisode {
			get {
				return ResourceManager.GetString("ExportFormatDateEpisode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} - {1}.
		/// </summary>
		internal static string ExportFormatEpisode {
			get {
				return ResourceManager.GetString("ExportFormatEpisode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} - s{3:00}e{4:00} - {1}.
		/// </summary>
		internal static string ExportFormatSeasonEpisode {
			get {
				return ResourceManager.GetString("ExportFormatSeasonEpisode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0}.
		/// </summary>
		internal static string ExportFormatTitle {
			get {
				return ResourceManager.GetString("ExportFormatTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} ({2:yyyy}).
		/// </summary>
		internal static string ExportFormatYear {
			get {
				return ResourceManager.GetString("ExportFormatYear", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose a file naming option..
		/// </summary>
		internal static string ExportInstructions {
			get {
				return ResourceManager.GetString("ExportInstructions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Dow&amp;nload....
		/// </summary>
		internal static string ExportMenu {
			get {
				return ResourceManager.GetString("ExportMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Video file format and extension will be left unchanged..
		/// </summary>
		internal static string ExportNote {
			get {
				return ResourceManager.GetString("ExportNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Airdate.
		/// </summary>
		internal static string ExportOptionDate {
			get {
				return ResourceManager.GetString("ExportOptionDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Airdate.
		/// </summary>
		internal static string ExportOptionDateEpisode {
			get {
				return ResourceManager.GetString("ExportOptionDateEpisode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Title - Subtitle.
		/// </summary>
		internal static string ExportOptionEpisode {
			get {
				return ResourceManager.GetString("ExportOptionEpisode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Season / Episode.
		/// </summary>
		internal static string ExportOptionSeasonEpisode {
			get {
				return ResourceManager.GetString("ExportOptionSeasonEpisode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Title.
		/// </summary>
		internal static string ExportOptionTitle {
			get {
				return ResourceManager.GetString("ExportOptionTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Year.
		/// </summary>
		internal static string ExportOptionYear {
			get {
				return ResourceManager.GetString("ExportOptionYear", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Download all episodes from this season with readable filenames..
		/// </summary>
		internal static string ExportSeasonTooltip {
			get {
				return ResourceManager.GetString("ExportSeasonTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Download all episodes from this show with readable filenames..
		/// </summary>
		internal static string ExportShowTooltip {
			get {
				return ResourceManager.GetString("ExportShowTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Dowload Recording.
		/// </summary>
		internal static string ExportTitle {
			get {
				return ResourceManager.GetString("ExportTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Play.
		/// </summary>
		internal static string PlayCaption {
			get {
				return ResourceManager.GetString("PlayCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Play {0} with the default player..
		/// </summary>
		internal static string PlayEpisodeTooltip {
			get {
				return ResourceManager.GetString("PlayEpisodeTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Play.
		/// </summary>
		internal static string PlayMenu {
			get {
				return ResourceManager.GetString("PlayMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Play next episode.
		/// </summary>
		internal static string PlayNextMenu {
			get {
				return ResourceManager.GetString("PlayNextMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Play next episode &amp;with....
		/// </summary>
		internal static string PlayNextWithMenu {
			get {
				return ResourceManager.GetString("PlayNextWithMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Play the oldest recorded episode of this season..
		/// </summary>
		internal static string PlaySeasonTooltip {
			get {
				return ResourceManager.GetString("PlaySeasonTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Play the oldest recorded episode of this show..
		/// </summary>
		internal static string PlayShowTooltip {
			get {
				return ResourceManager.GetString("PlayShowTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Play with....
		/// </summary>
		internal static string PlayWithCaption {
			get {
				return ResourceManager.GetString("PlayWithCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose an alternative player to play {0}..
		/// </summary>
		internal static string PlayWithEpisodeTooltip {
			get {
				return ResourceManager.GetString("PlayWithEpisodeTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Play &amp;with....
		/// </summary>
		internal static string PlayWithMenu {
			get {
				return ResourceManager.GetString("PlayWithMenu", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose an alternative player to play the oldest recorded episode of this season..
		/// </summary>
		internal static string PlayWithSeasonTooltip {
			get {
				return ResourceManager.GetString("PlayWithSeasonTooltip", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose an alternative player to play the oldest recorded episode of this show..
		/// </summary>
		internal static string PlayWithShowTooltip {
			get {
				return ResourceManager.GetString("PlayWithShowTooltip", resourceCulture);
			}
		}
	}
}
