//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace au.Applications.MythClient.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("au.Applications.MythClient.UI.InfoText", typeof(InfoText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours.
        /// </summary>
        internal static string DurationHours {
            get {
                return ResourceManager.GetString("DurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours {1:0} minutes.
        /// </summary>
        internal static string DurationHoursAndMinutes {
            get {
                return ResourceManager.GetString("DurationHoursAndMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minutes.
        /// </summary>
        internal static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1:d}.
        /// </summary>
        internal static string EpisodeNamelessTitle {
            get {
                return ResourceManager.GetString("EpisodeNamelessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode {0}.
        /// </summary>
        internal static string EpisodeNumber {
            get {
                return ResourceManager.GetString("EpisodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:  {1}.
        /// </summary>
        internal static string EpisodeTitle {
            get {
                return ResourceManager.GetString("EpisodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First aired {0:d}.
        /// </summary>
        internal static string FirstAired {
            get {
                return ResourceManager.GetString("FirstAired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1:yyyy}).
        /// </summary>
        internal static string MovieTitle {
            get {
                return ResourceManager.GetString("MovieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} episodes.
        /// </summary>
        internal static string NumEpisodes {
            get {
                return ResourceManager.GetString("NumEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seasons.
        /// </summary>
        internal static string NumSeasons {
            get {
                return ResourceManager.GetString("NumSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 episode.
        /// </summary>
        internal static string OneEpisode {
            get {
                return ResourceManager.GetString("OneEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 season.
        /// </summary>
        internal static string OneSeason {
            get {
                return ResourceManager.GetString("OneSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded {0:g}.
        /// </summary>
        internal static string Recorded {
            get {
                return ResourceManager.GetString("Recorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d} — {1:d}.
        /// </summary>
        internal static string RecordedRange {
            get {
                return ResourceManager.GetString("RecordedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}, episode {1}.
        /// </summary>
        internal static string SeasonNumberEpisodeNumber {
            get {
                return ResourceManager.GetString("SeasonNumberEpisodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Season {1}.
        /// </summary>
        internal static string SeasonTitle {
            get {
                return ResourceManager.GetString("SeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing in {0}.
        /// </summary>
        internal static string StillRecording {
            get {
                return ResourceManager.GetString("StillRecording", resourceCulture);
            }
        }
    }
}
